### ISSUE TITLE
Enhancements in next version

### ISSUE THREAD

**Issue by winderica** [UniqueStudio/UniqueRecruitmentSystem#1]
- 状态管理 **首要解决的问题**
    - [x] 目前版本中store的结构仍比较混乱，且在storage - state - data from server的过程中会产生一些bug
- 改进聊天室
    - ~@ 功能~： 优先级不高，且还要引入通知系统，先放一放。
    - [x] 组面：考虑google docs式的右侧边栏，这样还可以容纳一些东西
- 权限管理
    - [x] 需要限制访问自己所处的那次招新、跨组删除、发送短信等
    - 既然企业微信这块已经没问题了，那么就只需要后端适配就可以了
    - 由于之前用户可能没有填正确信息，且基本信息大概可以全部从企业微信获取了，考虑清一波users表
    - ~多组选手？~ 暂时搁置
- 考虑快通选手
    - [x] 这一块加一个字段就好了，主要是要招新表单增加这一项
- 改进面试分配界面
    - [x] 支持对单个选手的时间分配、发送短信操作
    - [x] 有时间的话还会做一个更人性化的界面
- 为移动端增加登录方法
    - [x] 这个也不是问题，id用微信提供的id，密码用户自己设置就好了
- ~操作日志~
    - 暂不考虑，有权限之后没多大意义
- 支持查看过往招新选手信息
    - [x] 目前版本只能查看进行中的招新，但是已留有相应余地
- ~多栏布局 -> 两栏布局？~
    - ~一般来说拖拽操作不会跨多个流程~
    - ~这样可以统合目前的`报名审核`与`群面审核`部分~
    - ~考虑 招新 -> 组别 -> 流程 的展示方式~
    - [x] 暂不考虑，最多会在选组别之前选招新
- 文档、注释
    - [x] 不太急，等一个接锅人
- [x] 修改招新信息
    - 笔试、面试时间在这里设置也会更加合理一些
- 优化性能
    - [x] 切换组别的时候会卡顿
    - [x] 首次加载较慢，gzip，入口组件单独加载
    - [x] h2，然而有时候好像不起作用
- 增强后端
    - [x] 单元测试
    - [x] 安全性
    - [x] ~不需要隐藏报名选手简历的路径，#2 第一点~
- 下载文件
    - ~进度条（用RxJS不太好做，鸽了~
    - ~考虑换一台服务器~

如果您有建设性的建议、意见，欢迎回复。

**Comment by winderica** [comment]
v3 todos
- [ ] 移动端没法拖了
- [ ] 换届后的信息更新问题

想到再加

**Comment by colinaaa** [comment]
新的组长会在扫码时通过企业微信拉取并更新数据库，新的管理员也可由管理员/组长设置。

暂时没想到更多的换届信息更新，欢迎补充。

**Comment by ManiaciaChao** [comment]
> 新的组长会在扫码时通过企业微信拉取并更新数据库，新的管理员也可由管理员/组长设置。
> 
> 暂时没想到更多的换届信息更新，欢迎补充。

移动组那边提议接入 lark，可以很方便地进行权限收敛，不过从企业微信迁移到 lark 的成本会很高。我觉得也可以通过企业微信中配置不同群组来实现。
