### ISSUE TITLE
Something needs to be improved

### ISSUE THREAD

**Issue by ttzztztz** [UniqueStudio/UniqueRecruitmentSystem#21]
- [x] Dark mode, menu icon disappeared
![image](https://user-images.githubusercontent.com/9049783/94246085-d8051d80-ff4d-11ea-901e-ebf89354194b.png)

- [x] Press enter to login in the password input box

- [ ] Improve data transfer. Pulling all data of one term from server may cause too many seconds waiting when the number of candidates is very high. Use cache and fetch data in the background or fetch less data from server per time.

**Comment by colinaaa** [comment]
我来！

**Comment by colinaaa** [comment]
目前的问题是，数据量大概在200KB左右，但是会出现TTFB多达数秒的情况，也会出现Download多达数秒的情况，后端服务（可能是服务器的锅）和带宽都不太行。

前端是有缓存的，不过存在了sessionStorage里，所以每次关闭页面后就删掉了。
当时为什么没有用localStorage呢？ 是想要每次都拉一边最新的数据么？ @winderica

目前考虑的做法是

- 从sessionStorage切换至localStorage
- 在后台拉取全量数据（或者候选人数据分组拉）
- 后端缓存热点数据

或者换台服务器...

\cc @ttzztztz @wangnengjie @ManiaciaChao

**Comment by winderica** [comment]
我忘了为什么，现在发现有点傻（

然而其实就算用了localStorage还是没从本质上解决问题，因为还是要拉一遍全量数据，只是用户体验稍微好一点。

之前说过，API设计的各种不合理。浏览某次招新的时候，我们只需要所有候选人的基本信息，只有当我们对某些候选人感兴趣的时候才会看他的详细信息，所以可以把原先的API拆成两个，分组拉也是可以的。不过感觉这种量级没必要缓存热点数据，可能更多的是代码写得有问题（

另外，也可以试一下JSON patch，就是迁移成本有点大。

**Comment by wangnengjie** [comment]
我和wqy讨论了一下。
一种方案是进入hr的时候，拉登陆者本组的候选人信息，查看的时候默认跳至本组（考虑到半数甚至更多情况下只会查看自己组的候选人）。当切换的时候再去拉其他组，这样比如这次200k的体量可以压到数十k。这种情况下，有些ws推来的信息是无用的。

另外我觉得拉全候选人信息其实还行（至少我经常点点点，体验很好...不知道其他组使用的时候是怎样的）

目前还没有测试造成时间较长是服务器问题还是server处理时间问题。

**Comment by winderica** [comment]
好！

但是如果我从查看本组切换到查看群面，就不能按组来处理了，需要单独考虑，否则就跟拉全量数据没区别。

**Comment by wangnengjie** [comment]
嗯，可以单独加一个api，群面人数较少不会有太大响应时间问题。emm，这样做可能需要稍微改下redux里candidate的结构，具体实现还有待讨论...

另外如果不是数据库查询时间的问题的话，没必要缓存热点数据。ms级的差距在目前能到6s甚至更长的停顿来看并不明显。

**Comment by ManiaciaChao** [comment]
其实200k的数据并不是非常多，只是1c1m的小水管服务器非常拉胯。现在团队有485小鸡，迁过去应该能治标。

即使是增量拉取数据也会比较麻烦，毕竟server需要拿uuid或者其他标识符来diff，server也得存之前的版本。

我个人倾向于先迁到大水管去，之后再做API拆分甚至重写这部分的逻辑。

**Comment by ManiaciaChao** [comment]
先展示 local state，同时拉新数据再更新也是比较好的解决方案（然而还是没有解决拉取慢的问题，只是ux大幅提升

**Comment by colinaaa** [comment]
按钮修复了

**Comment by ttzztztz** [comment]
> 按钮修复了

お疲れさんです

**Comment by colinaaa** [comment]
回车登录实现了

**Comment by ManiaciaChao** [comment]
`sessionStorage` was removed in #31
目前的方案是先读 `localStorage` 再拉数据 #35
