### ISSUE TITLE
Bug: Access mis-deny

### ISSUE THREAD

**Issue by xzcxzcyy** [UniqueStudio/UniqueRecruitmentSystem#57]
2021.9才进行企业微信登录的同学无法查看招新信息，即使加入时间是2020年秋招。

**Comment by colinaaa** [comment]
https://github.com/UniqueStudio/UniqueRecruitmentSystem/commit/d0351fdb651ea254e00c06076b57694bf4b9cf6a 问题出在这里

https://github.com/UniqueStudio/UniqueRecruitmentSystem/blob/6e0f8b43dd1a98e1afa988f5a43115e24b86639e/packages/backend/src/controllers/applications.controller.ts#L258-L260

这里当时为了少进行一次数据库查询，直接用了 `createdAt` 和 `updatedAt`，当时认为，member一定早于candidate被创建，没考虑到member早就加入，但一直没在hr系统创建账号的情况
